apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-secret-access-role
rules:
- apiGroups:
    - ""
  resources:
    - secrets
  verbs:
    - list
    - get
    - update
    - watch
    - create
