# permissions for end users to view gopassrepositories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gopassrepository-viewer-role
rules:
- apiGroups:
  - gopass.gopass.operator
  resources:
  - gopassrepositories
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gopass.gopass.operator
  resources:
  - gopassrepositories/status
  verbs:
  - get
